import React from "react"

const aboutUs = () =>(
    <>
      <h1>About Us</h1>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos, adipisci accusamus dolor porro veniam cum reprehenderit eligendi natus? Aperiam mollitia deserunt accusamus dolore harum ex distinctio, a quasi debitis vero nihil nostrum modi consequatur itaque nulla id vel delectus natus sed voluptatem, amet, eum eius? Quo voluptas quod, asperiores reprehenderit, aliquam, eaque quidem cupiditate tempore in ut deleniti odio debitis molestias illo officia dolor! Nulla quae necessitatibus vitae quibusdam ad, culpa inventore eaque numquam at molestias neque beatae saepe explicabo aut nam delectus hic error corporis? Minus omnis pariatur, et ab aspernatur ducimus dolorem asperiores vero rerum dolorum molestias deserunt.</p>
      <p>Porro corrupti odio eos placeat voluptatibus eveniet iure officia, harum eius optio commodi illum fugit aspernatur quae ab cumque soluta cupiditate? Magnam iure accusantium eius consequuntur eligendi nemo porro quod. Accusantium reiciendis rem iusto praesentium adipisci expedita, maiores at reprehenderit autem. Ipsum dolor cumque alias vel error aliquam, dolores voluptatum, officia quaerat voluptatem iure obcaecati? Assumenda modi voluptatem voluptatum praesentium? Nobis optio est, assumenda itaque ex doloremque cupiditate, nostrum odit quasi temporibus mollitia voluptatem deleniti. Ipsa laboriosam dolorem reiciendis pariatur, error nobis possimus fugit aliquid, doloremque cum quibusdam esse debitis quia consequuntur! Beatae fuga earum non nam est culpa tempore.</p>
      <p>Exercitationem at pariatur suscipit fuga nostrum cum, explicabo esse nisi deserunt odit dolore optio commodi accusamus. Corporis similique, velit unde voluptatem accusantium non ut voluptates facilis aliquam reprehenderit quod quos sed incidunt quas ipsum perferendis? Quasi architecto quam, dolorem laudantium obcaecati quisquam beatae. Illo adipisci ipsam fugit fuga, quis totam laudantium placeat. Quasi dolorem magni repellendus ipsam sequi iste magnam hic pariatur sapiente. Autem odio ullam vel explicabo ex facere suscipit eveniet. Minima, sed. Explicabo a corporis quos quisquam sit inventore, accusantium unde, sapiente, ab iusto deserunt. Maiores odio doloribus aliquid neque accusamus accusantium voluptatibus sit esse dolore aperiam. Vitae.</p>   
    </>
  );
export default aboutUs;